/**
 * Bakes the set of player tags a crawler is allowed to fetch.
 *
 * `/player/[tag]` is the most expensive route on the site — it renders per
 * request *and* makes an upstream API call — and the tag space is unbounded,
 * which is why `src/proxy.ts` 404s the whole prefix to crawlers. But it is also
 * the second most-visited content by real people, and none of it is indexable.
 *
 * The compromise is a bounded allowlist, and it has to be *baked* rather than
 * looked up: the proxy's `config.matcher` must be statically analysable, and
 * putting a database round trip on the hot path of every profile view to
 * decide whether to serve it would cost more than the crawl it prevents.
 *
 * The set is exactly the ranked leaderboard's top 100 — the same rows
 * `/leaderboard/ranked` renders, so every allowed URL is one the site already
 * links to. An allowlisted page nothing links to would just be an orphan with
 * extra steps.
 *
 * Fails safe. No database at build time (or any error at all) writes an empty
 * set, which means nothing is indexable — the crawl guard reverts to what it
 * was before this existed rather than opening up.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { getPrisma } from '../src/lib/prisma';

/** Matches RANKED_RESET_ELO in lib/stats: everyone lands on the floor. */
const RANKED_RESET_ELO = 750;
/** Matches the `limit` compute_getRankedLeaderboard defaults to. */
const TOP_N = 100;

const OUT = join(process.cwd(), 'src/generated/indexable-players.ts');

function write(tags: string[]): void {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(
    OUT,
    `// Generated by scripts/gen-indexable-players.ts. Do not edit.\n` +
      `// ${tags.length} tags, baked ${new Date().toISOString()}.\n` +
      `export const INDEXABLE_PLAYER_TAGS: ReadonlySet<string> = new Set(${JSON.stringify(tags)});\n`,
    'utf8',
  );
  console.log(`wrote ${tags.length} indexable player tags`);
}

async function main(): Promise<void> {
  const prisma = getPrisma();
  if (!prisma) {
    console.warn('no DATABASE_URL — writing an empty allowlist (nothing indexable)');
    write([]);
    return;
  }
  try {
    const rows = await prisma.sampledPlayer.findMany({
      where: { rankedElo: { gt: RANKED_RESET_ELO } },
      orderBy: [{ rankedElo: 'desc' }, { highestRankedElo: 'desc' }],
      take: TOP_N,
      select: { tag: true },
    });
    write(rows.map((row) => row.tag));
  } catch (error) {
    console.warn('query failed — writing an empty allowlist:', error);
    write([]);
  }
}

main().then(
  () => process.exit(0),
  (error) => {
    console.error(error);
    write([]);
    process.exit(0);
  },
);
